title: Kevin Mach # your name (or website title) here
logo: "/images/DSC02534insta.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently @ Seattle Pacific University
  <br><br>
  Bachelor of Science: Computer Science, Graduation 2021
  <br><br>
  Software Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-mach/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
